################################# Default configuration ###################
# provide your domain here
baseURL = "https://master.d2ifucdfz09ieg.amplifyapp.com/"
# theme
theme = "Dot"
# site title
title = "Easy ML PoCs"
# desable language
disableLanguages = []


[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = "monokai"
    tabWidth = 4

############################# Default Parameters ##########################
[params]
# logo is for all pages
logo = ""
# logo white is for homepage logo, you can use colorful logo too...
logo_white = ""
# when logo is empty, it will show your site title

# customize color
primary_color = "#02007e"
secondary_color = "#f9f9f9"
text_color = "#636363"
text_color_dark = "#242738"
white_color = "#ffffff"

# font family
font_family = "lato" # Choose font family from : https://fonts.google.com/

# contact form action
contact_form_action = "https://formspree.io/easy-ml-pocs@amazon.com"

# contact form works with : https://formspree.io

############################## social links ##############################
[[params.social]]
icon = "ti-facebook" # themify icon pack : https://themify.me/themify-icons
link = "#"

[[params.social]]
icon = "ti-twitter-alt" # themify icon pack : https://themify.me/themify-icons
link = "#"
  
[[params.social]]
icon = "ti-vimeo-alt" # themify icon pack : https://themify.me/themify-icons
link = "#"
  
[[params.social]]
icon = "ti-linkedin" # themify icon pack : https://themify.me/themify-icons
link = "#"


################################# navigation ################################
[[menu.main]]
name = "Faq"
url = "faq"
weight = 4

[[menu.main]]
name = "contact"
url = "contact"
weight = 5

# Dropdown menu
[[menu.main]]
weight = 3
name = "docs"
hasChildren = true

  [[menu.main]]
  parent = "docs"
  name = "Installation"
  url = "installation"
  weight = 1


# Code menu
[[menu.main]]
weight=1
name = "code"
hasChildren = true

  [[menu.main]]
  parent="code"
  name="Preprocessing"
  url="preprocessing"
  weight=1

  [[menu.main]]
  parent="code"
  name="Training"
  url="training"
  weight=2

  [[menu.main]]
  parent="code"
  name="Inference"
  url="inference"
  weight=3  

################################ English Language ######################
[Languages.en]
languageName = "En"
languageCode = "en-us"
weight = 1
home = "Home"
copyright = "Documents are copyright © AWS 2020."

# banner
[Languages.en.params.banner]
title = "How do I ..."
description = "Find code snippets you can use to build out your ML PoCs step-by-step"
bg_image = "images/banner.jpg"
placeholder = "Just ask here or enter terms"

# call to action
[Languages.en.params.cta]
enable = true
title = "Didn't find an answer to your question?"
description = "Contribute an answer or contact us for help."
[Languages.en.params.cta.button]
enable = true
label = "contact us"
link = "contact"





